### ISSUE TITLE
[MLIR] [Phase 3] Improve Triton unit test pass rate

### ISSUE THREAD

**Issue by rsanthanam-amd** [ROCmSoftwarePlatform/triton#10]
This task captures the effort to improve Triton unit test pass rate to 95% (from 90% in Phase 2) on gfx90a.

**Comment by B1tway** [comment]
test_core operators:
* AddPtrOp
* ArithConstantSplatOp
* BroadcastOp
* ConvertLayoutOp
* ElementWiseOp
* FuncOp
* GetProgramIdOp
* LoadOp
* MakeRangeOp
* ReduceOp
* ReturnOp
* SplatOp
* StoreOp
