### ISSUE TITLE
Make hardcoded ROCm path configurable

### ISSUE THREAD

**Issue by jglaser** [ROCmSoftwarePlatform/triton#149]
During code compilation in pytorch, I get the error that the linker `ld.lld` cannot be found.

This is due to the the hardcoded paths here
https://github.com/ROCmSoftwarePlatform/triton/blob/797737bccf61074ecdce450b72b677dfc26eee29/lib/Target/HSACO/HSACOTranslation.cpp#L137-L138
and here
https://github.com/ROCmSoftwarePlatform/triton/blob/797737bccf61074ecdce450b72b677dfc26eee29/scripts/amd/check_llvm_src.sh#L2

It would be nice if these could be made configurable via environment variables or during package installation.

I am using the triton pypi package that is installed with pytorch 2.0. I don't know which branch this corresponds to (in this repository?)

**Comment by rsanthanam-amd** [comment]
Hi,

Thanks for finding that oversight.

We have a PR with a fix targeted at our main dev branch `triton-mlir`.

The branch that is used for Pytorch 2.0 is `triton-mlir-pyt20`.

Once the PR lands in the main dev branch, we will cherry-pick the commit into the Pytorch 2.0 branch.

**Comment by rsanthanam-amd** [comment]
The fix for this has landed so closing this.
