### ISSUE TITLE
Benchmark triton flash attention against rocm flash attention standard algorithm

### ISSUE THREAD

**Issue by oplavsic** [ROCmSoftwarePlatform/triton#237]

**Comment by oplavsic** [comment]
batch size| sequence length | standard attention | rocm flash attention | triton flash attention MFMA | triton flash attention FMA|
-------------|------------------------|--------------------------|---------------------------|--------------------------------------|----------------------------------|
|       1      |            1024         | 448.71 us              |        344.10 us        |                5.67 ms                 |         6.60 ms                   |
|       1      |           2048          | 1.60 ms                 |      688.67 us          |              16.76 ms                 |         20.55 ms                 |
|       1      |         4096            | 6.29 ms                 |   1.79 ms                |       58.36 ms                        |         71.92 ms                 |
|       32    |            1024         |   13.42 ms             |      4.13 ms             |   135.29 ms                          |          165.99 ms              |
|       32    |            2048         | 57.72 ms               |   13.13 ms              |     471.71 ms                        |           584.18 ms             |
|       32    |            4096         |251.40 ms              |   54.97 ms              |           1.75 s                         |            2.20 s                   |
|       64    |            1024         | 30.28 ms               |    8.28 ms               |              268.88 ms               |            329.95 ms            |
|       64    |            2048         | 128.62 ms             |     29.09 ms            |           940.07 ms                  |             1.17 s                  |
|       64    |            4096         | 63.68 ms               |      16.65 ms           |              534.84 ms               |              655.43 ms          |

**Comment by oplavsic** [comment]
Benchmark done on MI210 GPU using benchmarking infrastructure from https://github.com/ROCmSoftwarePlatform/msft_amd_ai_operators/tree/master/operators/flash_attention.
Results after changes from https://github.com/ROCmSoftwarePlatform/triton/pull/247:

batch size| sequence length | standard attention | rocm flash attention | triton flash attention MFMA | triton flash attention FMA|
-------------|------------------------|--------------------------|---------------------------|--------------------------------------|----------------------------------|
|       1      |            1024         | 446.91 us              |        344.10 us        |                840.33 us                 |         6.60 ms                   |
|       1      |           2048          | 1.59 ms                 |      688.67 us          |              2.49 ms                 |         20.55 ms                 |
|       1      |         4096            | 8.76 ms                 |   1.79 ms                |       6.34 ms                        |         71.92 ms                 |
|       32    |            1024         |   13.47 ms             |      4.13 ms             |   21.25 ms                          |          165.99 ms              |
|       32    |            2048         |  51.45 ms              |   13.13 ms              |                      68.8 ms |           584.18 ms             |
|       32    |            4096         | 197.60 ms             |   54.97 ms              |            238.40 ms                  |            2.20 s                   |
|       64    |            1024         |  27.01 ms                |    8.28 ms               |                   40.92 ms          |            329.95 ms            |
|       64    |            2048         | 102.56 ms             |     29.09 ms            |           134.07 ms                  |             1.17 s                  |
|       128    |            1024        | 52.09 ms               |      16.65 ms           |              83.91 ms               |              655.43 ms          |

**Comment by oplavsic** [comment]
Results after changes from https://github.com/ROCmSoftwarePlatform/triton/pull/247 with reverted https://github.com/ROCmSoftwarePlatform/triton/pull/241 and WITH usage of pipelining optimization.

batch size| sequence length | standard attention | rocm flash attention | triton flash attention MFMA BLOCK = 64| triton flash attention MFMA BLOCK = 128|
-------------|------------------------|--------------------------|---------------------------|--------------------------------------|--------------------------------------------------|
|       1      |            1024         | 446.91 us              |        342.55 us        |                312.65 us               |         400.05 us                 |
|       1      |           2048          | 1.59 ms                 |      688.69 us          |              902.49 ms                 |                 1.02 ms         |
|       1      |         4096            |    6.34 ms              |   2.19 ms             |               2.77 ms                |         3.52 ms                 |
|       32    |            1024         |   13.47 ms             |     4.18 ms             |   7.72 ms                          |          8.88 ms              |
|       32    |            2048         |  51.45 ms              |   13.01 ms             |                      23.12 ms |           28.02  ms           |
|       32    |            4096         | 197.60 ms             |   47.30 ms             |            78.86 ms                  |              89.87  ms               |
|       64    |            1024         |  27.01 ms                |    8.18 ms               |                  14.25 ms          |            17.45   ms        |
|       64    |            2048         | 102.56 ms             |     25.90 ms            |           44.91 ms                  |             53.96     ms             |
|       128    |            1024        | 52.09 ms               |      16.07 ms           |              28.31 ms               |              35.00    ms       |

**Comment by zhanglx13** [comment]
@fxmarty 
We are using the [tutorial](https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/python/tutorials/06-fused-attention.py) as benchmark to collect performance numbers. You can change the parameters [here](https://github.com/ROCmSoftwarePlatform/triton/blob/9517d4c2566cd2763d038b95b79713a04a36eac6/python/tutorials/06-fused-attention.py#L737-L750) to run different configs.
