### ISSUE TITLE
Understand CK flash attention algorithm

### ISSUE THREAD

**Issue by oplavsic** [ROCmSoftwarePlatform/triton#238]
Investigate the code implemented in: https://github.com/ROCmSoftwarePlatform/flash-attention. Goal is to understand optimization that CK teams came up with in order to implement same optimizations in triton.

**Comment by zhanglx13** [comment]
Original CK's [slides](https://amdcloud.sharepoint.com/:p:/s/DNNFrameworkDevTeam/ET2frsd9TclLuyhbyzijfMcB5JaAat3_dtbknLNpvPXd5A?e=JxHNB3)
Our [proposal](https://amdcloud-my.sharepoint.com/:p:/g/personal/lixzhang_amd_com/EXGv7h8Uj59GhBjyIi1mgjcBnSAnvljRgfCEj1oCUokB2A?e=4%3AmPbgx7&at=9) to implement CK's tricks in Triton

**Comment by fxmarty** [comment]
@zhanglx13 Are these slides internal?

**Comment by zhanglx13** [comment]
@fxmarty Those slides about CK's FA are internal. 
@sunway513 Do we have any public introduction of CK team and their work?

**Comment by sunway513** [comment]
@asroy can you comment?
