### ISSUE TITLE
while loop fails on rocm triton but works on cuda

### ISSUE THREAD

**Issue by kailums** [ROCmSoftwarePlatform/triton#259]
HI guys

I was working on a kernel that using two level of while loop, but i found the script runs fine on cuda, fail on rocm.

I have written a little piece of code to reproduce it. 

This code is doing tensor add operation on multiple tensors, and  compare results with torch.

Since there are multiple tensors, I use one while loop on number of vector and then use another while to loop on vector_size.

each program is working on a BLOCK size of vector adding, after it finish one BLOCK, it add the number of programs, means moving to the next task. And the next task may be in the same vector or not.

```
import torch

import triton
import triton.language as tl


@triton.jit
def double_while_loop_vector_add(num_vec: tl.constexpr, vec_sizes, vec_a, vec_b, vec_res, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    num_pids = tl.num_programs(0)

    i = 0
    vec_size_sum = 0
    while i < num_vec:
        v_size = tl.load(vec_sizes + i)
        vec_size_next = vec_size_sum + v_size
        while pid >= vec_size_sum and pid < vec_size_next:
            A_ptr = vec_a + vec_size_sum
            B_ptr = vec_b + vec_size_sum
            res_ptr = vec_res + vec_size_sum

            pid_offset = pid - vec_size_sum
            vec_offset = pid_offset * BLOCK

            offset = pid_offset * BLOCK + tl.arange(0, BLOCK)
            data_a = tl.load(A_ptr + offset, mask=offset < v_size)
            data_b = tl.load(B_ptr + offset, mask=offset < v_size)

            data_res = data_a + data_b

            tl.store(res_ptr + offset, data_res, mask=offset < v_size)

            pid += num_pids     # this line of code seems not working on rocm

        i += 1
        vec_size_sum = vec_size_next

def triton_vec_add(vec_sizes, vec_a, vec_b):
    vec_res = torch.zeros_like(vec_a)
    grid = (100,)

    vec_sizes_tensor = torch.tensor(vec_sizes, dtype=torch.int32, device=vec_a.device)

    double_while_loop_vector_add[grid](len(vec_sizes),
        vec_sizes_tensor,
        vec_a,
        vec_b,
        vec_res,
        BLOCK=64)
    return vec_res

def torch_vec_add(vec_sizes, vec_a, vec_b):
    return vec_a + vec_b

def testcase_double_while(vec_sizes):
    vec_size = sum(vec_sizes)
    device = torch.device(0)
    vec_a = torch.randn(vec_size, device=device)
    vec_b = torch.randn(vec_size, device=device)

    triton_res = triton_vec_add(vec_sizes, vec_a, vec_b)
    torch_res = torch_vec_add(vec_sizes, vec_a, vec_b)

    if torch.allclose(triton_res, torch_res):
        print('Res is SAME.')
    else:
        print('Not SAME')
        print('triton: ', triton_res)
        print('torch: ', torch_res)

if __name__ == '__main__':
    testcase_double_while([96, 24, 128])

```

The result is SAME at cuda, but not same at rocm. It shows that only the first part of result vector has value, and the other part is zero.
<img width="623" alt="image" src="https://github.com/ROCmSoftwarePlatform/triton/assets/109063327/cf78230c-6d50-4b63-aa27-d6369b07edcd">

It seems the code `pid += num_pids` not works.

**Comment by scxiao** [comment]
Hi @kailums, PR https://github.com/ROCmSoftwarePlatform/triton/pull/271 is for this issue. You can apply this change to test your new implementation. Thanks.

**Comment by kailums** [comment]
Thanks @scxiao . I use your PR branch, and it works fine. And i also test the grouped_gemm kernel on MI200 with docker image: rocm/oai-triton:preview_2023-07-24_98, get perf result:
1. grouped_gemm_all_gpu.py, 649us
2. grouped_gemm_cpu_map.py, 596us

**Comment by scxiao** [comment]
Hi @kailums, thanks for the verification. Which input (row#) are these numbers corresponding to?

**Comment by kailums** [comment]
> Hi @kailums, thanks for the verification. Which input (row#) are these numbers corresponding to?

it's row8, with N align to 8.

**Comment by scxiao** [comment]
Bug fixed with PR https://github.com/ROCmSoftwarePlatform/triton/pull/271, so close it.
