### ISSUE TITLE
Incorrect fast conversion for fp8 e4m3

### ISSUE THREAD

**Issue by cloudhan** [ROCmSoftwarePlatform/triton#330]
The conversion forgot to add exponent compensation, so the conversion is not correct:

https://github.com/ROCmSoftwarePlatform/triton/blob/0cc3f8b84a16892396f6e08a04991034d67e32b1/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp#L183-L218

**Comment by cloudhan** [comment]
cc @zhangyaobit

**Comment by zhanglx13** [comment]
@scxiao Can you take a look?

**Comment by scxiao** [comment]
Hi @cloudhan, what do you mean for "exponent compensation"? Could you please give an example for that? Thanks

**Comment by scxiao** [comment]
> Hi @cloudhan, what do you mean for "exponent compensation"? Do you mean the exponent bias? Thanks
Hi @cloudhan, never mind, I figured it out. F8e4 and FP16 has different values of exponent bias, which needs an adjustment in the conversion. It seems like fp8e5 is fine since it has the same exponent bias 15 as fp16. Thanks for pointing this out. We will fix it.

**Comment by scxiao** [comment]
> > Hi @cloudhan, what do you mean for "exponent compensation"? Do you mean the exponent bias? Thanks
> > Hi @cloudhan, never mind, I figured it out. F8e4 and FP16 has different values of exponent bias, which needs an adjustment in the conversion. It seems like fp8e5 is fine since it has the same exponent bias 15 as fp16. Thanks for pointing this out. We will fix it.

Hi @cloudhan, some more update. Seem like our latest code already has the adjustment, please see: https://github.com/ROCmSoftwarePlatform/triton/blob/b25557ad5eb173a8a0680ed199954bf216448d2b/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp#L490. 

Thanks

Shucai
