### ISSUE TITLE
triton flash atten module generates NAN results

### ISSUE THREAD

**Issue by seungrokj** [ROCmSoftwarePlatform/triton#361]
Hi, 

Can somebody please take a look a this ?

I just tested this code and it generates NAN results. 

https://github.com/ROCmSoftwarePlatform/triton/blob/821e75a2b025c62e4fab0578e32a12b5ca5fc9e9/python/tutorials/06-fused-attention.py#L791C26-L791C26

==
**q**  torch.Size([1, 1, 32, 128])
tensor([[[[-0.6802, -1.0850, -0.0692,  ...,  0.6572, -0.5806,  0.9326],
          [-0.5576, -1.2197, -0.2014,  ..., -0.3674,  1.6328,  0.1525],
          [-0.6084,  1.6045, -0.9805,  ...,  0.8867, -0.7505,  1.2168],
          ...,
          [ 0.5347,  1.6855,  0.2388,  ...,  0.4429, -0.5376, -1.6738],
          [-0.1875, -1.4717,  1.2891,  ..., -1.4893, -0.0747,  0.1665],
          [-0.3394, -0.1830,  0.3008,  ..., -0.8252, -0.9717, -0.1410]]]],
       device='cuda:0', dtype=torch.float16, requires_grad=True)

**k**  torch.Size([1, 1, 32, 128])
tensor([[[[-0.0159, -1.1162, -0.0227,  ...,  0.1863,  1.1270,  0.4077],
          [ 0.4749,  0.0085, -1.2158,  ..., -0.6611,  1.1279, -0.6860],
          [-0.9087, -0.1031, -0.1813,  ..., -0.3081, -0.6235, -0.0531],
          ...,
          [ 1.9590,  0.4800, -0.7734,  ..., -0.4126,  0.2203,  0.0266],
          [ 1.0029, -0.2834,  0.9932,  ..., -0.3684, -0.0021,  0.8682],
          [ 0.5791,  0.5010,  0.5225,  ...,  0.9082, -1.0029, -0.4573]]]],
       device='cuda:0', dtype=torch.float16, requires_grad=True)

**v**  torch.Size([1, 1, 32, 128])
tensor([[[[ 0.3704,  0.8477,  0.5640,  ..., -0.8950, -0.3550,  1.3223],
          [-0.2488, -1.7812, -1.2598,  ..., -3.1172,  0.4167, -0.8350],
          [ 1.1592,  1.2959,  1.9062,  ...,  0.4001, -0.5503,  0.4915],
          ...,
          [-0.4038,  0.8740,  2.3984,  ..., -0.0678, -0.0503,  1.2686],
          [ 1.8193,  0.8252, -0.1876,  ...,  0.7461,  0.0269,  1.0889],
          [ 0.2830, -0.3262, -0.9536,  ...,  0.3835, -0.2573, -0.2834]]]],
       device='cuda:0', dtype=torch.float16, requires_grad=True)

**attn out**  torch.Size([1, 1, 32, 128])
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0',
       dtype=torch.float16, grad_fn=<_attentionBackward>)
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0',
       dtype=torch.float16, grad_fn=<_attentionBackward>)

**Comment by binarman** [comment]
hi @seungrokj !
I can not reproduce this error.
Could you elaborate, what GPU are you using and what exactly you are running?

**Comment by seungrokj** [comment]
@binarman 
Hi Alexander, 
The purpose of this is to check whether this FA2 triton kernel can be used for flashllama model in huggingface's transformers lib. 

My environment is like this:

**docker image:
rocm/pytorch:rocm5.7_ubuntu22.04_py3.10_pytorch_2.0.1
device: MI210
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import triton
>>> torch.__version__
'2.0.1+gita61a294'
>>> triton.__version__
'2.1.0'**

And I ran this code snippet: in ~/triton/python/tutorials/06-fused-attention.py
==
#bench_flash_attention.run(save_path='.', print_data=True)

for x in range(100):
    BATCH, H, N_CTX, D_HEAD = 1, 2, 32, 128
    dtype=torch.float16
    q = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
    k = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
    v = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
    sm_scale = 1.3
    split_kernel = False
    fn = lambda: attention(q, k, v, causal, sm_scale, split_kernel)
    out = attention(q, k, v, causal, sm_scale, split_kernel)
    print(out)

**Comment by vgokhale** [comment]
Hi @seungrokj,

Can you please set `causal = False` before calling `attention()`? That is the issue:

```
tensor([[[[ 0.3044,  0.6548, -0.0632,  ...,  0.3530, -1.1338,  0.3506],
          [ 1.2510, -0.8413, -0.1218,  ..., -0.1147, -0.3271,  0.2893],
          [-0.2256, -0.7344,  1.0557,  ..., -0.7852, -1.0244, -0.2084],
          ...,
          [ 1.0293, -0.2622,  0.3074,  ..., -0.9014,  2.6797, -0.3931],
          [-1.5938, -1.2783,  1.8682,  ..., -0.8115, -1.6621,  0.6128],
          [ 1.0381, -2.1133,  0.2771,  ..., -2.2520,  0.6777, -1.6592]],

         [[-0.3567, -0.8560, -0.5786,  ..., -0.1530, -1.4365, -1.6484],
          [ 0.3674,  0.4717, -0.0723,  ..., -0.1855, -0.2041,  1.8164],
          [ 0.5283,  0.0432,  0.8809,  ..., -0.4028, -0.1963, -0.0798],
          ...,
          [ 0.3010,  0.4788, -0.0402,  ..., -0.1376, -0.1702,  1.8770],
          [-0.5981, -1.0498, -0.0290,  ..., -1.3770, -1.2646, -1.1953],
          [-1.1260, -0.5132,  1.4346,  ..., -0.2590,  0.1078, -0.1565]]]],
       device='cuda:0', dtype=torch.float16, grad_fn=<_attentionBackward>)
```
