### ISSUE TITLE
[Phase 2] Implementation of Triton IR to RocDL

### ISSUE THREAD

**Issue by rsanthanam-amd** [ROCmSoftwarePlatform/triton#4]
This task captures the effort needed to convert the triton specific IR to RocDL MLIR.

**Comment by B1tway** [comment]
Expected working time: 2 weeks 
* Porting NVVM MLIR APIs to RocDL MLIR APIs **[Finished]**
* Porting PTX inline asm -> GCN inline asm **[In progress]**
