### ISSUE TITLE
Flash Attention Triton for Mi50s

### ISSUE THREAD

**Issue by ThePerfectComputer** [ROCmSoftwarePlatform/triton#461]
I'm sitting on a stockpile of AMD Mi50s. I've been unable to get flash attention to run on them. I'm wondering if there are any plans for a flash attention triton implementation. Perhaps one that will run on the Mi50s?

**Comment by zhanglx13** [comment]
@ThePerfectComputer Let me ask around if we still support MI50 GPUs.

**Comment by ThePerfectComputer** [comment]
Alright. Also, I'd be willing to pay for support for porting FA to the MI50.

**Comment by zhanglx13** [comment]
@ThePerfectComputer  Unfortunately we do not, and plan not to in the future, support FA on MI50 GPUs.

**Comment by cb88** [comment]
Apparently enablement is nearly trivial...  please apply so triton can actually be used for GPUs it can already work with.

https://github.com/lamikr/rocm_sdk_builder/commit/c337b2f5da1ebe9c5dcfc799a52e00020ffcf1c0#diff-6c8c5d41df041f13cdbb55ed8e7669bbf686e7093b8d7f3282001c7dada88dbaL39
