### ISSUE TITLE
[MLIR] [Phase 2] Implementation of RocDL MLIR to HSACO

### ISSUE THREAD

**Issue by rsanthanam-amd** [ROCmSoftwarePlatform/triton#5]
This task captures the effort needed to translate the RocDL MLIR to HSACO (AMDGCN).

**Comment by B1tway** [comment]
Expected working time: 1 week
* RocDL MLIR -> LLVM IR
* LLVM IR -> HSACO

**Comment by rsanthanam-amd** [comment]
@B1tway Do you have changes to enable AMDGCN generation for testing?

**Comment by B1tway** [comment]
@rsanthanam-amd I'm working on them and will do PR soon. I plan to add the AMDGCN target to `triton.tools.aot` so we can make similar PTX tests for AMDGCN.

**Comment by dfukalov** [comment]
Completed in a772241378240014f4b5cf9b35652aa1cc4aa05d.
