### ISSUE TITLE
[MLIR] [Phase 2] Porting and Verifying Triton GPU operations for AMDGPU

### ISSUE THREAD

**Issue by rsanthanam-amd** [ROCmSoftwarePlatform/triton#6]
This task captures the effort to map the math and device specific functions using the Triton IR --> RocDL MLIR --> AMDGCN pipeline.

**Comment by B1tway** [comment]
Different operators will require different time costs due to different complexity. Some operators that require MFMA will not be ported in phase 2

**Comment by whchung** [comment]
Done.
