### ISSUE TITLE
otherElems is a value or ptr

### ISSUE THREAD

**Issue by codego7250** [ROCmSoftwarePlatform/triton#62]
When reviewing the logic in https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir-phase-2/lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp#L1022
Here, otherElems is a Value as my understanding. This will be a bug when do load in LLVM.

**Comment by whchung** [comment]
I believe this has been addressed in #83 / #84 already. Closing the ticket hereby.
