### ISSUE TITLE
[MLIR] [Phase 2] Porting and enabling Triton unit tests for AMDGPU

### ISSUE THREAD

**Issue by rsanthanam-amd** [ROCmSoftwarePlatform/triton#7]
This task captures the effort for porting and enabling the Triton unit tests on AMDGPU.

The goal is a 90% unit test pass rate on gfx90a.

**Comment by B1tway** [comment]
* Porting lit tests for AMDGPU
* Porting python tests for AMDGPU

**Comment by B1tway** [comment]
test_core operators:
* AddPtrOp
* ArithConstantSplatOp
* BroadcastOp
* ConvertLayoutOp
* ElementWiseOp
* FuncOp
* GetProgramIdOp
* LoadOp
* MakeRangeOp
* ReduceOp
* ReturnOp
* SplatOp
* StoreOp

**Comment by dfukalov** [comment]
Online tests enabled since 28cfcfed55ce8c6f301d49d4dee274cc22d819b7.
